### ISSUE TITLE
Images are disappearing after a while of reloading.

### ISSUE THREAD

**Issue by shreeMahadikGit** [shreeMahadikGit/MEVN#1]
![image](https://user-images.githubusercontent.com/86063262/201595552-39ca2b77-4f3f-4585-8951-578e84dbd648.png)
![image](https://user-images.githubusercontent.com/86063262/201595617-d583cd8c-3320-4320-b1db-b95f1c2e82fe.png)
Even after **reloading and closing the window**, the photos continue to display.

However, when I go back to the **website an hour or so later**, this is what I see:
![image](https://user-images.githubusercontent.com/86063262/201595392-4a56df92-4c7e-4c6d-b769-fa7429bb6772.png)

I used Heroku (free tier) to host this site

**Comment by richardevcom** [comment]
For me, they don't load at atll.
Images are being loaded (`200` returned), but they are not defined via styling.

**Comment by shreeMahadikGit** [comment]
> For me, they don't load at atll. Images are being loaded (`200` returned), but they are not defined via styling.

Have any idea where's the issue? you can refer my code

**Comment by shreeMahadikGit** [comment]
Issue is due to Heroku. It doesn't support static files to be saved.
